#!/usr/bin/env python3
"""Send the daily Chase Sapphire deal digest email via Gmail SMTP."""

import os
import smtplib
import sys
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path


def load_credentials_file():
    """Load credentials.env from the repo root if it exists."""
    creds_file = Path(__file__).parent / "credentials.env"
    if creds_file.exists():
        for line in creds_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())


def build_html(body_content: str) -> str:
    today = date.today().strftime("%B %d, %Y")
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333; }}
    h1 {{ color: #1a1a2e; border-bottom: 2px solid #e8e8e8; padding-bottom: 10px; }}
    .date {{ color: #666; font-size: 14px; margin-bottom: 20px; }}
    .deal {{ margin-bottom: 16px; padding: 12px; background: #f9f9f9; border-left: 4px solid #0070ba; border-radius: 4px; }}
    .deal a {{ color: #0070ba; text-decoration: none; font-weight: bold; }}
    .deal a:hover {{ text-decoration: underline; }}
    .no-deals {{ color: #666; font-style: italic; }}
    .footer {{ margin-top: 30px; font-size: 12px; color: #999; border-top: 1px solid #e8e8e8; padding-top: 10px; }}
  </style>
</head>
<body>
  <h1>Chase Sapphire Deals</h1>
  <div class="date">{today}</div>
  {body_content}
  <div class="footer">Sourced from r/ChaseSapphire · Digest generated by Claude</div>
</body>
</html>"""


def main():
    if len(sys.argv) < 2:
        print("Usage: python send_email.py <html_body_content>")
        sys.exit(1)

    body_content = sys.argv[1]

    load_credentials_file()
    gmail_user = os.environ.get("GMAIL_USER")
    gmail_app_password = os.environ.get("GMAIL_APP_PASSWORD")
    email_to = os.environ.get("EMAIL_TO")

    if not all([gmail_user, gmail_app_password, email_to]):
        missing = [v for v, val in [("GMAIL_USER", gmail_user), ("GMAIL_APP_PASSWORD", gmail_app_password), ("EMAIL_TO", email_to)] if not val]
        print(f"Error: Missing environment variables: {', '.join(missing)}")
        sys.exit(1)

    today = date.today().strftime("%B %d, %Y")
    subject = f"Chase Sapphire Deals — {today}"
    html = build_html(body_content)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = email_to
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP("smtp.gmail.com", 587) as server:
            server.ehlo()
            server.starttls()
            server.login(gmail_user, gmail_app_password)
            server.sendmail(gmail_user, email_to, msg.as_string())
        print(f"Email sent to {email_to}: {subject}")
    except smtplib.SMTPAuthenticationError:
        print("Error: Gmail authentication failed. Check GMAIL_USER and GMAIL_APP_PASSWORD.")
        sys.exit(1)
    except smtplib.SMTPException as e:
        print(f"Error sending email: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
